# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], default=None, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=150)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('KM', 'Kms'), ('M', 'Miles')], default='KM', max_length=30)),
                ('race_date', models.DateField()),
                ('race_start', models.TimeField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bank_account', models.CharField(max_length=16)),
                ('presale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('attention', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Nom')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Prénom')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], default=None, max_length=1, null=True, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numéro de dossard')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timing.Category', verbose_name='Catégorie')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timing.Race', verbose_name='Course')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='timing.Runner'),
        ),
        migrations.AddField(
            model_name='payment',
            name='runner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='timing.Runner'),
        ),
    ]
