# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0002_runner_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de compte en banque'),
        ),
    ]
